"""change path to email

Revision ID: f784ac903ceb
Revises: d828e0b868f3
Create Date: 2024-10-31 17:08:49.069752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f784ac903ceb'
down_revision: Union[str, None] = 'd828e0b868f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('email', sa.String(), nullable=False))
    op.drop_column('User', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('User', 'email')
    # ### end Alembic commands ###
